Repository FastcampusMini/mini-project, pull requests merged in 2023-02, with the labels that each got.

#13 Feat product detail
  mini-project/.gitignore
  mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/ProductDetailDTO.java
  mini-project/src/main/java/com/fast/miniproject/product/service/ProductService.java
  mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java
Labels: For: API, For: Backend, Priority: Low, Status: Completed, Type: Feature

#18 feat: 금융상품 추천 기능 구현
  mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/ProductRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/service/ProductService.java
  mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java
Labels: For: API, For: Backend

#21 상품 구매 기능 구현
  mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/OrderDetail.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/ProductIdList.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/Order.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/OrderProductBridge.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/PurchasedProduct.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/OrderProductBridgeRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/OrderRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/ProductRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/PurchaseProductRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/service/ProductService.java
  mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java
Labels: For: API, For: Backend, Priority: High, Status: Completed, Type: Feature

#23 상품 구매 기록 조회
  mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/OrderDetail.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/Order.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/OrderProductBridge.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/PurchasedProduct.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/OrderProductBridgeRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/ProductRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/service/ProductService.java
  mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: On Hold, Type: Feature

#30 for loop 삭제 및 OrderEntity 주요 변경 사항
  mini-project/src/main/java/com/fast/miniproject/product/dto/OrderDetail.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/OrderListResp.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/OrderProductBridge.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/Orders.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/OrderProductBridgeRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/OrderRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java
Labels: For: API, For: Backend, Priority: High, Status: Completed, Type: Feature

#32 구매 상품 없는경우 예외처리
  mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java
Labels: For: Backend

#29 Feature/basket 장바구니 기능 구현
  mini-project/src/main/java/com/fast/miniproject/auth/entity/User.java
  mini-project/src/main/java/com/fast/miniproject/product/controller/BasketController.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/BasketAddRequestDTO.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/BasketDeleteRequestDTO.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/BasketResponseDTO.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/Basket.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/Product.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/BasketRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/ProductRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/service/BasketService.java
  mini-project/src/main/java/com/fast/miniproject/product/service/Impl/BasketServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#39 상품 주문, 조회, 삭제
  mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/OrderDetail.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/OrderHistory.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/OrderListResp.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/PurchasedProductDto.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/OrderProductBridge.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/Orders.java
  mini-project/src/main/java/com/fast/miniproject/product/entity/PurchasedProduct.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/OrderProductBridgeRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/OrderRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/ProductRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/PurchaseProductRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/service/ProductService.java
  mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java
Labels: For: Backend, Priority: High, Status: Completed, Type: Feature

#41 Swagger , 구매 추가 기능, json 파라메터 받기
  mini-project/src/main/java/com/fast/miniproject/product/controller/BasketController.java
  mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
  mini-project/src/main/java/com/fast/miniproject/product/repository/BasketRepository.java
  mini-project/src/main/java/com/fast/miniproject/product/service/impl/BasketServiceImpl.java
  mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java
  mini-project/src/main/java/com/fast/miniproject/search/controller/SearchProductController.java
Labels: For: API, For: Backend

#55 API rename
  mini-project/src/main/java/com/fast/miniproject/product/controller/BasketController.java
  mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
  mini-project/src/main/java/com/fast/miniproject/product/controller/WishlistController.java
Labels: For: API

#61 Feat 주문 삭제 요청 json 방식으로 변경
  mini-project/src/main/java/com/fast/miniproject/InitDb.java
  mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/DeleteOrdersIdReqDTO.java
Labels: For: API, For: Backend

#64 feat: 프론트 요청 사항 수정
  mini-project/src/main/java/com/fast/miniproject/product/dto/BasketResponseDTO.java
  mini-project/src/main/java/com/fast/miniproject/product/dto/WishlistResponseDTO.java
Labels: For: API, Priority: Low, Status: Completed, Type: Feature

#73 fix : swagger 테스트 IP 변경
  mini-project/src/main/java/com/fast/miniproject/global/config/SwaggerConfig.java
  mini-project/src/main/java/com/fast/miniproject/global/config/Workaround.java
Labels: For: Backend

#75 redis 도입 완료
  mini-project/src/main/java/com/fast/miniproject/auth/controller/AuthController.java
  mini-project/src/main/java/com/fast/miniproject/auth/dto/RefreshTokenReqDTO.java
  mini-project/src/main/java/com/fast/miniproject/auth/dto/TokenDTO.java
  mini-project/src/main/java/com/fast/miniproject/auth/entity/RefreshToken.java
  mini-project/src/main/java/com/fast/miniproject/auth/jwt/JwtExceptionFilter.java
  mini-project/src/main/java/com/fast/miniproject/auth/jwt/JwtFilter.java
  mini-project/src/main/java/com/fast/miniproject/auth/jwt/JwtProvider.java
  mini-project/src/main/java/com/fast/miniproject/auth/repository/RedisTemplateRepository.java
  mini-project/src/main/java/com/fast/miniproject/auth/repository/TokenRepository.java
  mini-project/src/main/java/com/fast/miniproject/auth/service/Impl/RefreshTokenServiceImpl.java
  mini-project/src/main/java/com/fast/miniproject/auth/service/Impl/TokenServiceImpl.java
  mini-project/src/main/java/com/fast/miniproject/auth/service/Impl/UserServiceImpl.java
  mini-project/src/main/java/com/fast/miniproject/auth/service/RefreshTokenService.java
  mini-project/src/main/java/com/fast/miniproject/auth/service/TokenService.java
  mini-project/src/main/java/com/fast/miniproject/global/config/SecurityConfig.java
  mini-project/src/main/java/com/fast/miniproject/global/config/SwaggerConfig.java
  mini-project/src/main/java/com/fast/miniproject/global/config/Workaround.java
Labels: For: API, For: Backend, Priority: Low, Status: Completed
